### ISSUE TITLE
I keep getting an unknown error 

### ISSUE THREAD

**Issue by Kashiu** [Xpl0itR/BetterDiscordPlugins#1]
Ngl theres a 95% chance I am just a fucking smooth brain but Imma ask for help anyways

**Comment by Xpl0itR** [comment]
You'll need to give me more info than that. Like a screenshot of the error

**Comment by Kashiu** [comment]
Ah sorry turns out my smooth brain forgot to add a token lemme remove the issue claim

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
