### ISSUE TITLE
Does this work anymore?

### ISSUE THREAD

**Issue by Neo-Nickz** [Xpl0itR/BetterDiscordPlugins#6]
seems like it isn't, honestly

**Comment by Neo-Nickz** [comment]
seems like it isn't honestly

**Comment by 21mtd** [comment]
it's auto claim nitro gifts, not auto "make" nitro, so you have to wait for someone to drop the gifts first. And also there are thousands of others using nitrosniper too so its all luck. I got 1 yesterday after installing it, pretty lucky i guess
